print("Dữ dội và dịu êm")
print("Ồn ào và lặng lẽ")
print("Sông không hiểu nổi mình")
print("Sông tìm ra tận bể")
print()
print("Ôi con sóng ngày xưa")
print("Và ngày sau vẫn thế")
print("Nỗi khát vọng tình yêu")
print("Bồi hồi trong ngực trẻ")
